name: Backend Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run CI
        run: npm ci

      - name: Run testing suite
        run: npm run test
        env:
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          ENVIROMENT: ${{ secrets.ENVIROMENT }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}

  prettier-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run CI
        run: npm ci

      - name: Run Prettier Check
        run: npm run prettier:check

  eslint-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run CI
        run: npm ci

      - name: Run Eslint Check
        run: npm run lint:check

  typescript-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run CI
        run: npm ci

      - name: Run Typescript Check
        run: npm run typescript:check
